# App server config for Nuxt
map $sent_http_content_type $expires {
   "text/html"                 epoch;
   "text/html; charset=utf-8"  epoch;
   default                     off;
}

# App server config for register SSL (Certbot)
server {
  listen      80;
  server_name .myphammuahe.live;

  client_max_body_size 64M;
  # server_names_hash_bucket_size 64;

  # Logs files
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  # Frontend files
  gzip            on;
  gzip_types      text/plain application/xml text/css application/javascript;
  gzip_min_length 1000;

  # Allow only for register SSL (Certbot)
  location ^~ /.well-known/acme-challenge { root /var/www/certbot; }

  # Redirect to HTTPS
  location / { return 301 https://$host$request_uri; }
}
